[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
